# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

#To Suppress all the Pod Warnings
inhibit_all_warnings!

target 'ProgressTrackerApp-iOS-UIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SwiftyRSA'
  pod 'lottie-ios', '4.1.2'
  pod 'Charts', '4.1.0'
end
